### ISSUE TITLE
Reactive collections

### ISSUE THREAD

**Issue by avalanche1** [peerlibrary/meteor-reactive-mongo#1]
Aren't collection queries reactive by default on the server?
In my proj they definitely are :smile:

**Comment by mitar** [comment]
Not that I would know. Show me an example. :-)

**Comment by nlhuykhang** [comment]
@avalanche1 yes, they are if you publish them in a normal way. When you want to do something more complicated inside publication, aggregation for example, there is no reactivity. That is where this package comes in.

**Comment by mitar** [comment]
Ah, yes. One cursor is reactive. Changes to documents will be published. But the query itself is not reactive. So results are reactive, but query is not. So if in the query you want some reactive variable you cannot do that.

**Comment by avalanche1** [comment]
Yep, exactly
